# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_data'),
        ('blog', '0003_market_data'),
    ]

    operations = [
    ]
