# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_merge_20171106_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market_data',
            name='at_file_name',
        ),
        migrations.RemoveField(
            model_name='market_data',
            name='download_link',
        ),
        migrations.AddField(
            model_name='market_data',
            name='at_file_name1',
            field=models.CharField(default='some', max_length=100),
        ),
        migrations.AddField(
            model_name='market_data',
            name='at_file_name2',
            field=models.CharField(default='some', max_length=100),
        ),
        migrations.AddField(
            model_name='market_data',
            name='at_file_name3',
            field=models.CharField(default='some', max_length=100),
        ),
        migrations.AddField(
            model_name='market_data',
            name='at_file_name4',
            field=models.CharField(default='some', max_length=100),
        ),
        migrations.AddField(
            model_name='market_data',
            name='download_link1',
            field=models.CharField(default='some', max_length=200),
        ),
        migrations.AddField(
            model_name='market_data',
            name='download_link2',
            field=models.CharField(default='some', max_length=200),
        ),
        migrations.AddField(
            model_name='market_data',
            name='download_link3',
            field=models.CharField(default='some', max_length=200),
        ),
        migrations.AddField(
            model_name='market_data',
            name='download_link4',
            field=models.CharField(default='some', max_length=200),
        ),
        migrations.AlterField(
            model_name='market_data',
            name='anchor',
            field=models.CharField(default='some', max_length=10),
        ),
    ]
