# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171108_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('at_file_name1', models.CharField(default='some', max_length=100)),
                ('at_file_name2', models.CharField(default='some', max_length=100)),
                ('at_file_name3', models.CharField(default='some', max_length=100)),
                ('at_file_name4', models.CharField(default='some', max_length=100)),
                ('download_link1', models.CharField(default='some', max_length=200)),
                ('download_link2', models.CharField(default='some', max_length=200)),
                ('download_link3', models.CharField(default='some', max_length=200)),
                ('download_link4', models.CharField(default='some', max_length=200)),
                ('anchor', models.CharField(default='some', max_length=10)),
            ],
        ),
    ]
